# Generated by Django 3.0 on 2020-11-01 17:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='required',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='survey',
            name='start_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 1, 18, 45, 6, 144325), help_text='survey starts accepting submissions on'),
        ),
    ]
