# Generated by Django 3.0 on 2020-11-01 18:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20201101_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('text', 'text'), ('radio', 'radio'), ('select', 'select'), ('select-multiple', 'select multiple'), ('integer', 'integer')], default='text', max_length=20),
        ),
        migrations.AlterField(
            model_name='survey',
            name='start_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 1, 19, 49, 7, 423765), help_text='survey starts accepting submissions on'),
        ),
    ]
